config/routes.rb
Rails.application.routes.draw do
  resources :cities
  #  get 'home/zipcode'
  root 'home#index'
  get 'zipcode' => 'home#index'
  post "zipcode" => 'home#zipcode'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def show
  end

  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City added'}
      else
        format.html {render :new }
      end
    end
  end

  private
  def city_params
    params.require(:city).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'



    @url = 'https://api.waqi.info/feed/beijing/?token=5bc9d9e4e31f41d07c589fae2cf23b4e2dfbbe90'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)

    if @output.empty?
        @final_output = "Error"
    else
        @final_output = @output['data']['aqi']
    end

    if @final_output == "Error"
      @api_color = "gray"
    elsif @final_output <= 50
      @api_color = "green"
      @api_description = "Air is clean, perfect for drinking coffee"
    elsif @final_output >= 51 && @final_output <= 100
      @api_color = "yellow"
      @api_description = "Air is ok, perfect for drinking coffee"
    elsif @final_output >= 101 && @final_output <= 150
      @api_color = "orange"
      @api_description = "Air is a bit shit, perfect for drinking coffee"
    elsif @final_output >= 151 && @final_output <= 200
      @api_color = "red"
      @api_description = "Air is getting dirty, perfect for drinking coffee"
    elsif @final_output >= 201 && @final_output <= 300
      @api_color = "purple"
      @api_description = "Air is real bad, perfect for drinking coffee"
    elsif @final_output >= 301 && @final_output <= 500
      @api_color = "maroon"
      @api_description = "Air is total shite, perfect for drinking coffee"
    end
  end

  def zipcode
    @zip_query = params[:zipcode]
    if params[:zipcode] === ""
      @final_output = "Empty search field"
    elsif params[:zipcode]
      #do API stuff


      require 'net/http'
      require 'json'

      @url = 'https://api.waqi.info/feed/'+ @zip_query + '/?token=5bc9d9e4e31f41d07c589fae2cf23b4e2dfbbe90'
      @uri = URI(@url)
      @response = Net::HTTP.get_response(@uri)

      @output = JSON.parse(@response.body)

      if @output['status'] === "ok"
        @final_output = @output['data']['aqi']
        @city = @output['data']['city']['name']  
      else
        @final_output = "Error"
        @city = "Please enter a city or location"  
      end

      if @final_output == "Error"
        @api_color = "gray"
      elsif @final_output <= 50
        @api_color = "green"
        @api_description = "Air is clean, perfect for drinking coffee"
      elsif @final_output >= 51 && @final_output <= 100
        @api_color = "yellow"
        @api_description = "Air is ok, perfect for drinking coffee"
      elsif @final_output >= 101 && @final_output <= 150
        @api_color = "orange"
        @api_description = "Air is a bit shit, perfect for drinking coffee"
      elsif @final_output >= 151 && @final_output <= 200
        @api_color = "red"
        @api_description = "Air is getting dirty, perfect for drinking coffee"
      elsif @final_output >= 201 && @final_output <= 300
        @api_color = "purple"
        @api_description = "Air is real bad, perfect for drinking coffee"
      elsif @final_output >= 301 && @final_output <= 500
        @api_color = "maroon"
        @api_description = "Air is total shite, perfect for drinking coffee"
      end


    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br/>
  <div class="field">
    <%= form.text_field :city, class:"form-control", placeholder: "Enter City" %>
  </div>

<br/>
  <%= submit_tag 'Add', class: "btn btn-secondary" %>
<% end %>
<br/>

app/views/cities/index.html.erb
<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>City</th>
      <th>AQI</th>
    </tr>
  </thead>
  <tbody>
  <% @cities.each do |city| %>
    <% @url = 'https://api.waqi.info/feed/'+ city.name + '/?token=5bc9d9e4e31f41d07c589fae2cf23b4e2dfbbe90' %>
    <% @uri = URI(@url) %>
    <% @response = Net::HTTP.get(@uri) %>
    <% @output = JSON.parse(@response) %>
    <tr>
      <td><%= city.name %></td>
      <td style="background-color:<%= @api_color %>;"><%= @output['data']['aqi'] %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'Add a City', new_city_path, class: "btn btn-secondary" %>

app/views/cities/new.html.erb
<div class="container">
  <div class="col-md-6 offset-md-3">
    
      <center><h1>Add a city</h1></center>

      <%= render 'form', city: @city %>

      <%= link_to 'Back', cities_path %>
    
  </div>
</div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "AirQualityIndex", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">



    </ul>
    <%= form_tag zipcode_path, :method => 'POST' do %>
    <div class="form-inline my-2 my-lg-0">
      <%= text_field_tag 'zipcode', nil, placeholder: "search city", class: "form-control mr-sm-2" %>
      <%= submit_tag 'Search', class: "btn btn-outline-success my-2 my-sm-0"%>

    <% end %>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p class="lead"><%= @api_description %></p>
  <hr class="my-4">
  <p>This is the current air quality index for <strong>Beijing, China</strong></p>
</div>

<br/>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p class="lead"><%= @api_description %></p>
  <hr class="my-4">
  <p>This is the current air quality index for the city of <strong><%= @city %></strong></p>
</div>

<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AQI</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <br/><br/><br/>
      <%= yield %>
    </div>
  </body>
</html>